### PR TITLE
refactor: add generic type for resource keys

### PR DESCRIPTION
**Pull request by sdcdsvsdv423**
This pull request allows you to specify the type for the resource keys.

Screenshot 2021-01-22 at 21 26 03

### CODE REVIEW

**Comment by EdJoPaTo** [comment]
I like the idea! I will check on it when I find the time. Thanks for bringing this up! :)

**Comment by EdJoPaTo** [comment]
Your first commit 4c242fa introduced a set of improvements, 0edbee4 changes a lot of things unrelated unrelated to the generic resource key typings. Changes like filepaths, linting and so on are not the point of this PR?

**Comment by sdcdsvsdv423** [comment]
No, it's only https://github.com/EdJoPaTo/telegraf-i18n/pull/3/commits/4c242fa818e837214b051f91bfa039de86676f59 commit related to the pull request.

**Comment by EdJoPaTo** [comment]
Then you commited to the wrong branch as the commit ended up in the branch of the pull request

**Comment by sdcdsvsdv423** [comment]
I can close this pull request for now and make another one later. Actually, I found a better approach where checking types not only for resource keys but also for parameters. But it needs more testing.

This is a template parser, which create types for each template: https://github.com/esindger/telegraf-i18n/blob/master/src/generateTypes.ts

Parsing output looks like this:
```ts
export interface ResourceParams {
  'greeting': never
  'cart': {
    apples: string | number | Record<string, unknown>
    pluralize: (...args: any[]) => string
  }
}
```

Then the `t` method definition should be like this:

```ts
export type RepositoryData = Record<string, Record<string, unknown> | never>

export class I18nContext<RepositoryT = RepositoryData> {
  // ...
  
  t<T extends keyof RepositoryT>(resourceKey: T, templateData?: Readonly<RepositoryT[T]>) {
    // 
  }
}

// Create instance
const i18nContext = new I18nContext<ResourceParams> ({
  // config
})
```

**Pull request closed without merging**
